[package]
name = "niri-zvim-zellij"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Zellij adapter plugin for niri-zvim"
readme = "../../README.md"
publish = false

[dependencies]
niri-zvim-core = { version = "0.1.0", path = "../core" }
serde_json.workspace = true
zellij-tile.workspace = true

[[bin]]
name = "niri-zvim-zellij"
path = "src/main.rs"
test = false
bench = false
